all:
  hosts:
    192.168.1.169:
      ansible_host: 192.168.1.169
    frank2:
      ansible_host: 192.168.1.169
    garage-mon:
      ansible_host: 192.168.1.169
    lenovoserver:
      ansible_host: localhost
    nasomv:
      ansible_host: 192.168.1.194
  children: {}
