- hosts: mcmyadmin
  become: yes
  tasks:
  - name: install openjdk 11
    apt: name=openjdk-11-jdk state=present
  - name: Create mcmyadmin directory
    file:
      path: /home/pi/McMyAdmin
      state: directory
#  - name: copy over etc.zip
#    copy:
#      src: playfiles/mcmyadmin/etc.zip
#      dest: /usr/local/etc.zip
#      owner: root
#      group: root
#      mode: '0644'
  - name: copy over configScript
    copy:
      src: playfiles/mcmyadmin/configScript.sh
      dest: /home/pi/McMyAdmin/configScript.sh
      owner: pi
      group: pi
      mode: '0644'
  - name: unzip mcmyadmin
    unarchive:
      src: playfiles/mcmyadmin/MCMA2_glibc26_2.zip
      dest: /home/pi/McMyAdmin/
#      remote_src: yes
  - name: unzip etc file
    unarchive:
      src: playfiles/mcmyadmin/etc.zip
      dest: /usr/local/
#      remote_src: yes
  - name: fix permissions for MCMA2
    file: dest=/home/pi/McMyAdmin owner=pi group=pi mode=0755 recurse=yes
  - name: fix permissions for etc folder
    file: dest=/usr/local/etc owner=root group=root mode=0755 recurse=yes
#not working
#  - name: set config password to Fuller98
#    command: /home/pi/McMyAdmin/./configScript.sh
