---
- hosts: all
  become: yes
  tasks:
    - name: Copy OpenSSH config
      copy:
        src: ../playfiles/openssh-config/sshd_config
        dest: /etc/ssh/sshd_config

    - name: Find all .pub files in keys folder on control host
      delegate_to: localhost
      run_once: true
      find:
        paths: "../playfiles/openssh-config/keys"
        patterns: '*.pub'
        file_type: file
      register: pub_key_files

    - name: Set up SSH keys from control host
      authorized_key:
        user: dadisc01
        state: present
        key: "{{ lookup('file', item.path) }}"
      loop: "{{ pub_key_files.files }}"
      loop_control:
        label: "{{ item.path }}"


    - name: Ensure SSH keypair exists on remote
      shell: test -f /home/dadisc01/.ssh/id_rsa || ssh-keygen -q -t rsa -N "" -f /home/dadisc01/.ssh/id_rsa >/dev/null 2>&1
      changed_when: false

    - name: Collect keys for new machines
      fetch:
        src: /home/dadisc01/.ssh/id_rsa.pub
        dest: ../playfiles/openssh-config/newKeys/{{ inventory_hostname }}.pub
        flat: yes
      ignore_errors: yes

